apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: indexer
  description: Indexer component
  tags:
    - golang
  links:
    - url: https://syntio.atlassian.net/wiki/spaces/SP/pages/1242923116/Persistor+-+Solution#Indexer
      title: Documentation
      icon: docs
spec:
  type: service
  lifecycle: production
  system: persistor-system
  owner: Persistor
  providesApi: 
  - api:indexer-api
  dependencyOf:
  - component:persistor-core
