apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: indexer
  description: Indexer component
  tags:
    - golang
    - http-restful
    - server
  annotations: 
    github.com/project-slug: https://github.com/syntio/aquarium-janitor-standalone-sr
  links:
    - url: https://syntio.atlassian.net/wiki/spaces/SJ/pages/1960738817/User+Documentation#Architecture-and-Components
      title: Documentation
      icon: docs
spec:
  type: service
  lifecycle: production
  system: persistor-system
  owner: Persistor
  dependsOn:
  - resource:schema-history
  - component:compatibility-checker
  - component:validity-checker
  providesApi: 
  - api:registry-api