apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resubmitter
  description: Resubmitter component
  tags:
    - golang
  links:
    - url: https://syntio.atlassian.net/wiki/spaces/SP/pages/1242923116/Persistor+-+Solution#Resubmitter
      title: Documentation
      icon: docs
spec:
  type: service
  lifecycle: production
  system: persistor-system
  owner: Persistor
  dependsOn:
  - component:indexer-api
  providesApi: 
  - api:resubmitter-api
